version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_DATABASE: meubanco
    volumes:
      - ./database/banco.sql:/docker-entrypoint-initdb.d/banco.sql
    networks:
      - redeapp

  php1:
    build: ./app
    depends_on:
      - mysql
    networks:
      - redeapp

  php2:
    build: ./app
    depends_on:
      - mysql
    networks:
      - redeapp

  php3:
    build: ./app
    depends_on:
      - mysql
    networks:
      - redeapp

  nginx:
    image: nginx
    ports:
      - "4500:4500"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php1
      - php2
      - php3
    networks:
      - redeapp

networks:
  redeapp:
    driver: bridge
